FavoriteItemDao =
  find: () ->
    [
      {
        name:"store1"
        description:"広島で2番目にうまくて安い店"
        latitude:35.6586
        longitude:139.745
        image:'../KS_nav_views.png'
      }
      {
        name:"store2"
        description:"福岡で2番目にうまくて安い店"
        latitude:35.6586
        longitude:139.745
        image:'../KS_nav_views.png'
      }
      {
        name:"store3"
        description:"東京で2番目にうまくて安い店"
        latitude:35.6586
        longitude:139.745
        image:'../KS_nav_views.png'
      }
      {
        name:"store4"
        description:"大阪で2番目にうまくて安い店"
        latitude:35.6586
        longitude:139.745
        image:'../KS_nav_views.png'
      }
      {
        name:"store4"
        description:"北海道で2番目にうまくて安い店"
        latitude:35.6586
        longitude:139.745
        image:'../KS_nav_views.png'
      }
    ]
